definitions:
  models.PagedResponse:
    properties:
      data:
        type: object
      total:
        type: integer
    type: object
  sysRole.AddRoleRequest:
    properties:
      available:
        description: 是否可用 0 不可用 1 可用
        type: integer
      description:
        description: 角色描述
        type: string
      name:
        description: 角色名称
        type: string
    required:
    - available
    - description
    - name
    type: object
  sysRole.RoleWithChecked:
    properties:
      available:
        type: integer
      checked:
        type: boolean
      create_time:
        description: 添加时间
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        description: 角色名
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  sysRole.SysRole:
    properties:
      available:
        type: integer
      create_time:
        description: 添加时间
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        description: 角色名
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  sysRole.UpdateRoleRequest:
    properties:
      available:
        description: 是否可用 0 不可用 1 可用
        type: integer
      description:
        description: 角色描述
        type: string
      id:
        type: integer
      name:
        description: 角色名称
        type: string
    required:
    - available
    - description
    - name
    type: object
  sysUser.AddUserRequest:
    properties:
      email:
        description: 邮箱地址
        type: string
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      password:
        description: 登录密码
        type: string
      qq:
        description: QQ
        type: string
      reg_ip:
        description: 注册IP
        type: string
      username:
        type: string
    required:
    - nickname
    - password
    - username
    type: object
  sysUser.SysUser:
    properties:
      avatar:
        description: 头像地址
        type: string
      birthday:
        description: 生日
        type: string
      blog:
        description: 个人博客地址
        type: string
      company:
        description: 公司
        type: string
      create_time:
        description: 注册时间
        type: string
      email:
        description: 邮箱地址
        type: string
      experience:
        description: 经验值
        type: integer
      gender:
        description: 性别
        type: integer
      id:
        type: integer
      last_login_ip:
        description: 最近登录IP
        type: string
      last_login_time:
        description: 最近登录时间
        type: string
      location:
        description: 地址
        type: string
      login_count:
        description: 登录次数
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      notification:
        description: 通知：(1：通知显示消息详情，2：通知不显示详情)
        type: integer
      password:
        description: 登录密码
        type: string
      privacy:
        description: 隐私（1：公开，0：不公开）
        type: integer
      qq:
        description: QQ
        type: string
      reg_ip:
        description: 注册IP
        type: string
      remark:
        description: 用户备注
        type: string
      score:
        description: 金币值
        type: integer
      source:
        description: 用户来源
        type: string
      status:
        description: 用户状态
        type: integer
      update_time:
        description: 更新时间
        type: string
      user_type:
        description: 超级管理员、管理员、普通用户
        type: string
      username:
        type: string
      uuid:
        description: 用户唯一表示(第三方网站)
        type: string
    type: object
  sysUser.UpdatePasswordByIdRequest:
    properties:
      id:
        type: integer
      new_password:
        description: 新密码
        type: string
      new_password_again:
        description: 新密码
        type: string
      password:
        description: 当前密码
        type: string
      username:
        type: string
    type: object
  sysUser.UpdateUserRequest:
    properties:
      email:
        description: 邮箱地址
        type: string
      id:
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      qq:
        description: QQ
        type: string
    type: object
info:
  contact: {}
  title: 用户中心API
  version: "1.0"
paths:
  /roles:
    get:
      description: 角色列表
      parameters:
      - default: 1
        description: pageIndex
        in: query
        name: pageIndex
        type: number
      - default: 10
        description: pageSize
        in: query
        name: pageSize
        type: number
      - description: 关键词
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.PagedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/sysRole.SysRole'
                  type: array
              type: object
      summary: 角色列表
      tags:
      - 角色
    post:
      description: 角色列表
      parameters:
      - description: 添加角色
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/sysRole.AddRoleRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加角色
      tags:
      - 角色
  /roles/{id}:
    delete:
      description: 根据id更新角色
      parameters:
      - description: id
        in: path
        name: id
        type: number
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据id删除角色
      tags:
      - 角色
    get:
      description: 根据id获取角色信息
      parameters:
      - description: id
        in: path
        name: id
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sysRole.SysRole'
      summary: 根据id获取角色信息
      tags:
      - 角色
    put:
      description: 根据id更新角色
      parameters:
      - description: id
        in: path
        name: id
        type: number
      - description: 更新角色
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sysRole.UpdateRoleRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据id更新角色
      tags:
      - 角色
  /users:
    get:
      description: 用户列表
      parameters:
      - default: 1
        description: pageIndex
        in: query
        name: pageIndex
        type: number
      - default: 10
        description: pageSize
        in: query
        name: pageSize
        type: number
      - description: 关键词
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.PagedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/sysUser.SysUser'
                  type: array
              type: object
      summary: 用户列表
      tags:
      - 用户
    post:
      description: 角色用户
      parameters:
      - description: 添加用户
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/sysUser.AddUserRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加用户
      tags:
      - 用户
  /users/{id}:
    delete:
      description: 删除用户
      parameters:
      - description: id
        in: path
        name: id
        type: number
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
    get:
      description: 根据id获取用户信息
      parameters:
      - description: id
        in: path
        name: id
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sysUser.SysUser'
      summary: 根据id获取用户信息
      tags:
      - 用户
    put:
      description: 根据id更新用户
      parameters:
      - description: id
        in: path
        name: id
        type: number
      - description: 更新用户
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sysUser.UpdateUserRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据id更新用户
      tags:
      - 用户
  /users/{id}/attr/password:
    put:
      description: 更新用户密码
      parameters:
      - description: id
        in: path
        name: id
        type: number
      - description: 更新用户密码
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sysUser.UpdatePasswordByIdRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 更新用户密码
      tags:
      - 用户
  /users/{id}/roles:
    put:
      description: 更新用户角色
      parameters:
      - description: id
        in: path
        name: id
        type: number
      - description: 更新用户密码
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sysUser.UpdatePasswordByIdRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 更新用户角色
      tags:
      - 用户
swagger: "2.0"
